DEEPSEEK_API_KEY = "sk-6dd54c30e1934c938b10cf1806b296f2"

SMTP2GO_HOST = "mail.smtp2go.com"
SMTP2GO_PORT = "2525"
SMTP2GO_USER = "zcfttq1@ucl.ac.uk"
SMTP2GO_PASSWORD = "Qitianni2007"
SMTP2GO_FROM = "zcfttq1@ucl.ac.uk"
SMTP2GO_FROM_NAME = "K1netix"
